### ISSUE TITLE
I can't connect, keep getting 'Internal server error' messages

### ISSUE THREAD

**Issue by slchorne** [slchorne/nimob#1]
After I have created a login account, I can't see any of the grid details and after a few seconds i get a popup saying "Internal server error"

**Comment by slchorne** [comment]
This is related to a bug in the NIOS WAPI, and things like mobile safari not liking self signed certificates. The cause of the error goes like this:

If you load the app from a server with a self signed cert, and that cert is not in your browser's whitelist it will kill your session. It won't let any AJAX calls happen because the browser doesn't trust the server.

if the cert is ok, you can still get a problem if you messed up the login and typed something like 'Admin' instead of 'admin'. Logins on the WAPI are CASE SENSITIVE, but once you've put in a bad credential one of 2 hings can still happen:
- your browser can reject the cert and or the session, leading to the above 'no AJAX' issue
- you browser can be passing a BAD cookie (ibapauth) that was created by the WAPI server and the server
  is rejecting all requests.

So what you you do ?
- wait for your session to time out
- edit your account, and put in the CORRECT credentials
- cross your fingers.

The more diags i can get on this, the more i can try and work around it.

**Comment by pjvogelsang** [comment]
Had some of these issues with the default browser on my Samsung Galaxy 3. Installed firefox browser and is working fine.
