### ISSUE TITLE
Authorization required: incorrect client access method apparently_via=API

### ISSUE THREAD

**Issue by bepstein** [slchorne/nimob#4]
Running: 6.10.3-231468
Installed via instructions in readme.

I log into the interface, but am greeted with "Error https://ipam.example.com/wapi/v1.2/networkview Authorization Required" with Firefox 22.0.

Looking at the log, I see the following

Admin: ep
LOGIN_DENIED
Execution Status: normal
to=AdminConnector
ip=1.2.3.4
auth=LOCAL
group=network
info=Incorrect client access method apparently_via=API:

Do I need to allow the API calls or something for nimob?  ibcli is working just fine with the same user.

Thanks,
ep

**Comment by slchorne** [comment]
correct, you need to enable API access

**Comment by bepstein** [comment]
Can you give me a hint?  I'm having trouble finding where to enable the API access and Google hasn't been very helpful in this regard.

Thanks,
ep

**Comment by slchorne** [comment]
I came across a new update on this, it depends on the browser. the XSS protection still fights nimob. Sometime you have to go to 'https://ipam.example.com/wapi/v1.2/' from the browser to get it to accept the certificate and suchlike. After that NiMob sees to work better.

But i need more data to nail down the exact cause.
